//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizerDemo.Localizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ar_LY {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ar_LY() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizerDemo.Localizer.Resources.ar-LY", typeof(Resources_ar_LY).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتدل الحرارة.
        /// </summary>
        internal static string Balmy {
            get {
                return ResourceManager.GetString("Balmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منعش.
        /// </summary>
        internal static string Bracing {
            get {
                return ResourceManager.GetString("Bracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارد.
        /// </summary>
        internal static string Chilly {
            get {
                return ResourceManager.GetString("Chilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارد.
        /// </summary>
        internal static string Cool {
            get {
                return ResourceManager.GetString("Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجميد.
        /// </summary>
        internal static string Freezing {
            get {
                return ResourceManager.GetString("Freezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حار.
        /// </summary>
        internal static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتدل.
        /// </summary>
        internal static string Mild {
            get {
                return ResourceManager.GetString("Mild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محترق.
        /// </summary>
        internal static string Scorching {
            get {
                return ResourceManager.GetString("Scorching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملخص.
        /// </summary>
        internal static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لافح.
        /// </summary>
        internal static string Sweltering {
            get {
                return ResourceManager.GetString("Sweltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الحرارة.
        /// </summary>
        internal static string tempratureC {
            get {
                return ResourceManager.GetString("tempratureC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الحرارة فهرنهايت .
        /// </summary>
        internal static string tempratureF {
            get {
                return ResourceManager.GetString("tempratureF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دافئ.
        /// </summary>
        internal static string Warm {
            get {
                return ResourceManager.GetString("Warm", resourceCulture);
            }
        }
    }
}
